package planfilter

import "testing"

// Golden test for plan gating, generated from the reference implementation's
// compiled output (@mars-sea/dsh-commandcode-provider@0.12.4) run against a
// real 87-model live catalog snapshot.
//
// The expected sets below are NOT hand-written: they are the reference's own
// answers for the same catalog. Hand-writing them would only re-test my
// reading of the spec; these catch a port that diverges from the authority.

// liveCatalog87 is a real snapshot of GET {base-url}/models.
var liveCatalog87 = []string{
	"claude-sonnet-5-5",
	"claude-sonnet-5",
	"claude-sonnet-4-6",
	"claude-fable-5-1",
	"claude-fable-5",
	"claude-opus-5-5",
	"claude-opus-5",
	"claude-opus-4-8",
	"claude-opus-4-7",
	"claude-haiku-5-5",
	"claude-haiku-4-5-20251001",
	"gpt-6-astra",
	"gpt-6.1-sol",
	"gpt-6-sol",
	"gpt-6-luna",
	"gpt-5.6-sol",
	"gpt-5.6-terra",
	"gpt-5.6-luna",
	"gpt-5.5",
	"gpt-5.4",
	"gpt-5.3-codex",
	"gpt-5.4-mini",
	"deepseek/deepseek-v4-pro",
	"deepseek/deepseek-v4-flash",
	"deepseek/deepseek-v4-flash-vision-exp",
	"deepseek/deepseek-v4-flash-fast",
	"deepseek/deepseek-v4.1-flash",
	"deepseek/deepseek-v4.1-flash-fast",
	"moonshotai/Kimi-K3",
	"moonshotai/Kimi-K2.7-Code",
	"moonshotai/Kimi-K2.7-Code-Highspeed",
	"moonshotai/Kimi-K2.6",
	"moonshotai/Kimi-K2.5",
	"z-ai/glm-5.3-flash",
	"z-ai/glm-5.3-flashx",
	"zai-org/GLM-5.3",
	"zai-org/GLM-5.2",
	"zai-org/GLM-5.2-Fast",
	"zai-org/GLM-5.1",
	"zai-org/GLM-5",
	"MiniMaxAI/MiniMax-M3",
	"MiniMaxAI/MiniMax-M2.7",
	"MiniMaxAI/MiniMax-M2.5",
	"xiaomi/mimo-v2.6-pro",
	"xiaomi/mimo-v2.6-pro-ultraspeed",
	"xiaomi/mimo-v2.6-flash",
	"xiaomi/mimo-v2.5-pro",
	"xiaomi/mimo-v2.5",
	"Qwen/Qwen3.8-Omni-Flash",
	"Qwen/Qwen3.8-Max-0902",
	"Qwen/Qwen3.8-Max",
	"Qwen/Qwen3.8-27B",
	"Qwen/Qwen3.8-Flash",
	"Qwen/Qwen3.7-Max",
	"Qwen/Qwen3.7-Plus",
	"Qwen/Qwen3.7-Flash",
	"Qwen/Qwen3.6-Max-Preview",
	"Qwen/Qwen3.6-Plus",
	"meituan/LongCat-2.0",
	"stepfun/Step-5-Preview",
	"stepfun/Step-3.7-Flash",
	"stepfun/Step-3.5-Flash",
	"tencent/hy3-paid",
	"tencent/hy4-preview",
	"google/gemini-3.8-flash",
	"google/gemini-3.7-flash",
	"google/gemini-3.6-flash",
	"google/gemini-3.5-flash",
	"google/gemini-3.5-flash-lite",
	"google/gemini-3.1-flash-lite",
	"sakana/fugu-ultra",
	"nvidia/nemotron-3-ultra-550b-a55b",
	"thinkingmachines/inkling",
	"thinkingmachines/inkling-small",
	"stealth/glyph-cluster:free",
	"poolside/laguna-s-2.1-free",
	"inclusionai/ling-3.0-flash-sante:free",
	"inclusionai/ling-3.1-flash:free",
	"meta/muse-spark-1.1",
	"meta/muse-spark-1.2",
	"meta/muse-spark-1.2-contributor",
	"meta/muse-spark-1.3",
	"meta/muse-spark-1.3-contributor",
	"xai/grok-4.5",
	"xai/grok-4.6",
	"xai/grok-4.7",
	"mistral/mistral-large-4",
}

// wantVisibleByPlan is the reference implementation's visible set for each
// planId, against liveCatalog87.
var wantVisibleByPlan = map[string][]string{
	"individual-go": {
		"claude-haiku-5-5",
		"gpt-6-luna",
		"gpt-5.6-luna",
		"deepseek/deepseek-v4-pro",
		"deepseek/deepseek-v4-flash",
		"deepseek/deepseek-v4-flash-vision-exp",
		"deepseek/deepseek-v4-flash-fast",
		"deepseek/deepseek-v4.1-flash",
		"deepseek/deepseek-v4.1-flash-fast",
		"moonshotai/Kimi-K3",
		"moonshotai/Kimi-K2.7-Code",
		"moonshotai/Kimi-K2.7-Code-Highspeed",
		"moonshotai/Kimi-K2.6",
		"moonshotai/Kimi-K2.5",
		"z-ai/glm-5.3-flash",
		"z-ai/glm-5.3-flashx",
		"zai-org/GLM-5.3",
		"zai-org/GLM-5.2",
		"zai-org/GLM-5.2-Fast",
		"zai-org/GLM-5.1",
		"zai-org/GLM-5",
		"MiniMaxAI/MiniMax-M3",
		"MiniMaxAI/MiniMax-M2.7",
		"MiniMaxAI/MiniMax-M2.5",
		"xiaomi/mimo-v2.6-pro",
		"xiaomi/mimo-v2.6-flash",
		"xiaomi/mimo-v2.5-pro",
		"xiaomi/mimo-v2.5",
		"Qwen/Qwen3.8-Omni-Flash",
		"Qwen/Qwen3.8-Max-0902",
		"Qwen/Qwen3.8-Max",
		"Qwen/Qwen3.8-27B",
		"Qwen/Qwen3.8-Flash",
		"Qwen/Qwen3.7-Max",
		"Qwen/Qwen3.7-Plus",
		"Qwen/Qwen3.7-Flash",
		"Qwen/Qwen3.6-Max-Preview",
		"Qwen/Qwen3.6-Plus",
		"meituan/LongCat-2.0",
		"stepfun/Step-5-Preview",
		"stepfun/Step-3.7-Flash",
		"stepfun/Step-3.5-Flash",
		"tencent/hy3-paid",
		"tencent/hy4-preview",
		"nvidia/nemotron-3-ultra-550b-a55b",
		"thinkingmachines/inkling",
		"thinkingmachines/inkling-small",
		"stealth/glyph-cluster:free",
		"poolside/laguna-s-2.1-free",
		"inclusionai/ling-3.0-flash-sante:free",
		"inclusionai/ling-3.1-flash:free",
		"meta/muse-spark-1.2-contributor",
		"meta/muse-spark-1.3-contributor",
		"xai/grok-4.5",
		"mistral/mistral-large-4",
	},
	"individual-go-v1": {
		"claude-haiku-5-5",
		"gpt-6-luna",
		"gpt-5.6-luna",
		"deepseek/deepseek-v4-pro",
		"deepseek/deepseek-v4-flash",
		"deepseek/deepseek-v4-flash-vision-exp",
		"deepseek/deepseek-v4-flash-fast",
		"deepseek/deepseek-v4.1-flash",
		"deepseek/deepseek-v4.1-flash-fast",
		"moonshotai/Kimi-K3",
		"moonshotai/Kimi-K2.7-Code",
		"moonshotai/Kimi-K2.7-Code-Highspeed",
		"moonshotai/Kimi-K2.6",
		"moonshotai/Kimi-K2.5",
		"z-ai/glm-5.3-flash",
		"z-ai/glm-5.3-flashx",
		"zai-org/GLM-5.3",
		"zai-org/GLM-5.2",
		"zai-org/GLM-5.2-Fast",
		"zai-org/GLM-5.1",
		"zai-org/GLM-5",
		"MiniMaxAI/MiniMax-M3",
		"MiniMaxAI/MiniMax-M2.7",
		"MiniMaxAI/MiniMax-M2.5",
		"xiaomi/mimo-v2.6-pro",
		"xiaomi/mimo-v2.6-flash",
		"xiaomi/mimo-v2.5-pro",
		"xiaomi/mimo-v2.5",
		"Qwen/Qwen3.8-Omni-Flash",
		"Qwen/Qwen3.8-Max-0902",
		"Qwen/Qwen3.8-Max",
		"Qwen/Qwen3.8-27B",
		"Qwen/Qwen3.8-Flash",
		"Qwen/Qwen3.7-Max",
		"Qwen/Qwen3.7-Plus",
		"Qwen/Qwen3.7-Flash",
		"Qwen/Qwen3.6-Max-Preview",
		"Qwen/Qwen3.6-Plus",
		"meituan/LongCat-2.0",
		"stepfun/Step-5-Preview",
		"stepfun/Step-3.7-Flash",
		"stepfun/Step-3.5-Flash",
		"tencent/hy3-paid",
		"tencent/hy4-preview",
		"nvidia/nemotron-3-ultra-550b-a55b",
		"thinkingmachines/inkling",
		"thinkingmachines/inkling-small",
		"stealth/glyph-cluster:free",
		"poolside/laguna-s-2.1-free",
		"inclusionai/ling-3.0-flash-sante:free",
		"inclusionai/ling-3.1-flash:free",
		"meta/muse-spark-1.2-contributor",
		"meta/muse-spark-1.3-contributor",
		"xai/grok-4.5",
		"mistral/mistral-large-4",
	},
	"individual-goat": {
		"claude-sonnet-5-5",
		"claude-haiku-5-5",
		"gpt-6-luna",
		"gpt-5.6-sol",
		"gpt-5.6-luna",
		"deepseek/deepseek-v4-pro",
		"deepseek/deepseek-v4-flash",
		"deepseek/deepseek-v4-flash-vision-exp",
		"deepseek/deepseek-v4-flash-fast",
		"deepseek/deepseek-v4.1-flash",
		"deepseek/deepseek-v4.1-flash-fast",
		"moonshotai/Kimi-K3",
		"moonshotai/Kimi-K2.7-Code",
		"moonshotai/Kimi-K2.7-Code-Highspeed",
		"moonshotai/Kimi-K2.6",
		"moonshotai/Kimi-K2.5",
		"z-ai/glm-5.3-flash",
		"z-ai/glm-5.3-flashx",
		"zai-org/GLM-5.3",
		"zai-org/GLM-5.2",
		"zai-org/GLM-5.2-Fast",
		"zai-org/GLM-5.1",
		"zai-org/GLM-5",
		"MiniMaxAI/MiniMax-M3",
		"MiniMaxAI/MiniMax-M2.7",
		"MiniMaxAI/MiniMax-M2.5",
		"xiaomi/mimo-v2.6-pro",
		"xiaomi/mimo-v2.6-pro-ultraspeed",
		"xiaomi/mimo-v2.6-flash",
		"xiaomi/mimo-v2.5-pro",
		"xiaomi/mimo-v2.5",
		"Qwen/Qwen3.8-Omni-Flash",
		"Qwen/Qwen3.8-Max-0902",
		"Qwen/Qwen3.8-Max",
		"Qwen/Qwen3.8-27B",
		"Qwen/Qwen3.8-Flash",
		"Qwen/Qwen3.7-Max",
		"Qwen/Qwen3.7-Plus",
		"Qwen/Qwen3.7-Flash",
		"Qwen/Qwen3.6-Max-Preview",
		"Qwen/Qwen3.6-Plus",
		"meituan/LongCat-2.0",
		"stepfun/Step-5-Preview",
		"stepfun/Step-3.7-Flash",
		"stepfun/Step-3.5-Flash",
		"tencent/hy3-paid",
		"tencent/hy4-preview",
		"google/gemini-3.8-flash",
		"google/gemini-3.7-flash",
		"nvidia/nemotron-3-ultra-550b-a55b",
		"thinkingmachines/inkling",
		"thinkingmachines/inkling-small",
		"stealth/glyph-cluster:free",
		"poolside/laguna-s-2.1-free",
		"inclusionai/ling-3.0-flash-sante:free",
		"inclusionai/ling-3.1-flash:free",
		"meta/muse-spark-1.2",
		"meta/muse-spark-1.2-contributor",
		"meta/muse-spark-1.3",
		"meta/muse-spark-1.3-contributor",
		"xai/grok-4.5",
		"xai/grok-4.6",
		"xai/grok-4.7",
		"mistral/mistral-large-4",
	},
	"individual-pro": {
		"claude-sonnet-5-5",
		"claude-sonnet-5",
		"claude-sonnet-4-6",
		"claude-haiku-5-5",
		"claude-haiku-4-5-20251001",
		"gpt-6-sol",
		"gpt-6-luna",
		"gpt-5.6-sol",
		"gpt-5.6-terra",
		"gpt-5.6-luna",
		"gpt-5.5",
		"gpt-5.4",
		"gpt-5.3-codex",
		"gpt-5.4-mini",
		"deepseek/deepseek-v4-pro",
		"deepseek/deepseek-v4-flash",
		"deepseek/deepseek-v4-flash-vision-exp",
		"deepseek/deepseek-v4-flash-fast",
		"deepseek/deepseek-v4.1-flash",
		"deepseek/deepseek-v4.1-flash-fast",
		"moonshotai/Kimi-K3",
		"moonshotai/Kimi-K2.7-Code",
		"moonshotai/Kimi-K2.7-Code-Highspeed",
		"moonshotai/Kimi-K2.6",
		"moonshotai/Kimi-K2.5",
		"z-ai/glm-5.3-flash",
		"z-ai/glm-5.3-flashx",
		"zai-org/GLM-5.3",
		"zai-org/GLM-5.2",
		"zai-org/GLM-5.2-Fast",
		"zai-org/GLM-5.1",
		"zai-org/GLM-5",
		"MiniMaxAI/MiniMax-M3",
		"MiniMaxAI/MiniMax-M2.7",
		"MiniMaxAI/MiniMax-M2.5",
		"xiaomi/mimo-v2.6-pro",
		"xiaomi/mimo-v2.6-pro-ultraspeed",
		"xiaomi/mimo-v2.6-flash",
		"xiaomi/mimo-v2.5-pro",
		"xiaomi/mimo-v2.5",
		"Qwen/Qwen3.8-Omni-Flash",
		"Qwen/Qwen3.8-Max-0902",
		"Qwen/Qwen3.8-Max",
		"Qwen/Qwen3.8-27B",
		"Qwen/Qwen3.8-Flash",
		"Qwen/Qwen3.7-Max",
		"Qwen/Qwen3.7-Plus",
		"Qwen/Qwen3.7-Flash",
		"Qwen/Qwen3.6-Max-Preview",
		"Qwen/Qwen3.6-Plus",
		"meituan/LongCat-2.0",
		"stepfun/Step-5-Preview",
		"stepfun/Step-3.7-Flash",
		"stepfun/Step-3.5-Flash",
		"tencent/hy3-paid",
		"tencent/hy4-preview",
		"google/gemini-3.8-flash",
		"google/gemini-3.7-flash",
		"google/gemini-3.6-flash",
		"google/gemini-3.5-flash",
		"google/gemini-3.5-flash-lite",
		"google/gemini-3.1-flash-lite",
		"nvidia/nemotron-3-ultra-550b-a55b",
		"thinkingmachines/inkling",
		"thinkingmachines/inkling-small",
		"stealth/glyph-cluster:free",
		"poolside/laguna-s-2.1-free",
		"inclusionai/ling-3.0-flash-sante:free",
		"inclusionai/ling-3.1-flash:free",
		"meta/muse-spark-1.1",
		"meta/muse-spark-1.2",
		"meta/muse-spark-1.2-contributor",
		"meta/muse-spark-1.3",
		"meta/muse-spark-1.3-contributor",
		"xai/grok-4.5",
		"xai/grok-4.6",
		"xai/grok-4.7",
		"mistral/mistral-large-4",
	},
	"individual-pro-v1": {
		"claude-sonnet-5-5",
		"claude-sonnet-5",
		"claude-sonnet-4-6",
		"claude-haiku-5-5",
		"claude-haiku-4-5-20251001",
		"gpt-6-sol",
		"gpt-6-luna",
		"gpt-5.6-sol",
		"gpt-5.6-terra",
		"gpt-5.6-luna",
		"gpt-5.5",
		"gpt-5.4",
		"gpt-5.3-codex",
		"gpt-5.4-mini",
		"deepseek/deepseek-v4-pro",
		"deepseek/deepseek-v4-flash",
		"deepseek/deepseek-v4-flash-vision-exp",
		"deepseek/deepseek-v4-flash-fast",
		"deepseek/deepseek-v4.1-flash",
		"deepseek/deepseek-v4.1-flash-fast",
		"moonshotai/Kimi-K3",
		"moonshotai/Kimi-K2.7-Code",
		"moonshotai/Kimi-K2.7-Code-Highspeed",
		"moonshotai/Kimi-K2.6",
		"moonshotai/Kimi-K2.5",
		"z-ai/glm-5.3-flash",
		"z-ai/glm-5.3-flashx",
		"zai-org/GLM-5.3",
		"zai-org/GLM-5.2",
		"zai-org/GLM-5.2-Fast",
		"zai-org/GLM-5.1",
		"zai-org/GLM-5",
		"MiniMaxAI/MiniMax-M3",
		"MiniMaxAI/MiniMax-M2.7",
		"MiniMaxAI/MiniMax-M2.5",
		"xiaomi/mimo-v2.6-pro",
		"xiaomi/mimo-v2.6-pro-ultraspeed",
		"xiaomi/mimo-v2.6-flash",
		"xiaomi/mimo-v2.5-pro",
		"xiaomi/mimo-v2.5",
		"Qwen/Qwen3.8-Omni-Flash",
		"Qwen/Qwen3.8-Max-0902",
		"Qwen/Qwen3.8-Max",
		"Qwen/Qwen3.8-27B",
		"Qwen/Qwen3.8-Flash",
		"Qwen/Qwen3.7-Max",
		"Qwen/Qwen3.7-Plus",
		"Qwen/Qwen3.7-Flash",
		"Qwen/Qwen3.6-Max-Preview",
		"Qwen/Qwen3.6-Plus",
		"meituan/LongCat-2.0",
		"stepfun/Step-5-Preview",
		"stepfun/Step-3.7-Flash",
		"stepfun/Step-3.5-Flash",
		"tencent/hy3-paid",
		"tencent/hy4-preview",
		"google/gemini-3.8-flash",
		"google/gemini-3.7-flash",
		"google/gemini-3.6-flash",
		"google/gemini-3.5-flash",
		"google/gemini-3.5-flash-lite",
		"google/gemini-3.1-flash-lite",
		"nvidia/nemotron-3-ultra-550b-a55b",
		"thinkingmachines/inkling",
		"thinkingmachines/inkling-small",
		"stealth/glyph-cluster:free",
		"poolside/laguna-s-2.1-free",
		"inclusionai/ling-3.0-flash-sante:free",
		"inclusionai/ling-3.1-flash:free",
		"meta/muse-spark-1.1",
		"meta/muse-spark-1.2",
		"meta/muse-spark-1.2-contributor",
		"meta/muse-spark-1.3",
		"meta/muse-spark-1.3-contributor",
		"xai/grok-4.5",
		"xai/grok-4.6",
		"xai/grok-4.7",
		"mistral/mistral-large-4",
	},
	"individual-provider": {
		"claude-sonnet-5-5",
		"claude-sonnet-5",
		"claude-sonnet-4-6",
		"claude-fable-5-1",
		"claude-fable-5",
		"claude-opus-5-5",
		"claude-opus-5",
		"claude-opus-4-8",
		"claude-opus-4-7",
		"claude-haiku-5-5",
		"claude-haiku-4-5-20251001",
		"gpt-6-astra",
		"gpt-6-sol",
		"gpt-6-luna",
		"gpt-5.6-sol",
		"gpt-5.6-terra",
		"gpt-5.6-luna",
		"gpt-5.5",
		"gpt-5.4",
		"gpt-5.3-codex",
		"gpt-5.4-mini",
		"deepseek/deepseek-v4-pro",
		"deepseek/deepseek-v4-flash",
		"deepseek/deepseek-v4-flash-vision-exp",
		"deepseek/deepseek-v4-flash-fast",
		"deepseek/deepseek-v4.1-flash",
		"deepseek/deepseek-v4.1-flash-fast",
		"moonshotai/Kimi-K3",
		"moonshotai/Kimi-K2.7-Code",
		"moonshotai/Kimi-K2.7-Code-Highspeed",
		"moonshotai/Kimi-K2.6",
		"moonshotai/Kimi-K2.5",
		"z-ai/glm-5.3-flash",
		"z-ai/glm-5.3-flashx",
		"zai-org/GLM-5.3",
		"zai-org/GLM-5.2",
		"zai-org/GLM-5.2-Fast",
		"zai-org/GLM-5.1",
		"zai-org/GLM-5",
		"MiniMaxAI/MiniMax-M3",
		"MiniMaxAI/MiniMax-M2.7",
		"MiniMaxAI/MiniMax-M2.5",
		"xiaomi/mimo-v2.6-pro",
		"xiaomi/mimo-v2.6-pro-ultraspeed",
		"xiaomi/mimo-v2.6-flash",
		"xiaomi/mimo-v2.5-pro",
		"xiaomi/mimo-v2.5",
		"Qwen/Qwen3.8-Omni-Flash",
		"Qwen/Qwen3.8-Max-0902",
		"Qwen/Qwen3.8-Max",
		"Qwen/Qwen3.8-27B",
		"Qwen/Qwen3.8-Flash",
		"Qwen/Qwen3.7-Max",
		"Qwen/Qwen3.7-Plus",
		"Qwen/Qwen3.7-Flash",
		"Qwen/Qwen3.6-Max-Preview",
		"Qwen/Qwen3.6-Plus",
		"meituan/LongCat-2.0",
		"stepfun/Step-5-Preview",
		"stepfun/Step-3.7-Flash",
		"stepfun/Step-3.5-Flash",
		"tencent/hy3-paid",
		"tencent/hy4-preview",
		"google/gemini-3.8-flash",
		"google/gemini-3.7-flash",
		"google/gemini-3.6-flash",
		"google/gemini-3.5-flash",
		"google/gemini-3.5-flash-lite",
		"google/gemini-3.1-flash-lite",
		"sakana/fugu-ultra",
		"nvidia/nemotron-3-ultra-550b-a55b",
		"thinkingmachines/inkling",
		"thinkingmachines/inkling-small",
		"stealth/glyph-cluster:free",
		"poolside/laguna-s-2.1-free",
		"inclusionai/ling-3.0-flash-sante:free",
		"inclusionai/ling-3.1-flash:free",
		"meta/muse-spark-1.1",
		"meta/muse-spark-1.2",
		"meta/muse-spark-1.2-contributor",
		"meta/muse-spark-1.3",
		"meta/muse-spark-1.3-contributor",
		"xai/grok-4.5",
		"xai/grok-4.6",
		"xai/grok-4.7",
		"mistral/mistral-large-4",
	},
	"individual-max": {
		"claude-sonnet-5-5",
		"claude-sonnet-5",
		"claude-sonnet-4-6",
		"claude-fable-5-1",
		"claude-fable-5",
		"claude-opus-5-5",
		"claude-opus-5",
		"claude-opus-4-8",
		"claude-opus-4-7",
		"claude-haiku-5-5",
		"claude-haiku-4-5-20251001",
		"gpt-6-astra",
		"gpt-6.1-sol",
		"gpt-6-sol",
		"gpt-6-luna",
		"gpt-5.6-sol",
		"gpt-5.6-terra",
		"gpt-5.6-luna",
		"gpt-5.5",
		"gpt-5.4",
		"gpt-5.3-codex",
		"gpt-5.4-mini",
		"deepseek/deepseek-v4-pro",
		"deepseek/deepseek-v4-flash",
		"deepseek/deepseek-v4-flash-vision-exp",
		"deepseek/deepseek-v4-flash-fast",
		"deepseek/deepseek-v4.1-flash",
		"deepseek/deepseek-v4.1-flash-fast",
		"moonshotai/Kimi-K3",
		"moonshotai/Kimi-K2.7-Code",
		"moonshotai/Kimi-K2.7-Code-Highspeed",
		"moonshotai/Kimi-K2.6",
		"moonshotai/Kimi-K2.5",
		"z-ai/glm-5.3-flash",
		"z-ai/glm-5.3-flashx",
		"zai-org/GLM-5.3",
		"zai-org/GLM-5.2",
		"zai-org/GLM-5.2-Fast",
		"zai-org/GLM-5.1",
		"zai-org/GLM-5",
		"MiniMaxAI/MiniMax-M3",
		"MiniMaxAI/MiniMax-M2.7",
		"MiniMaxAI/MiniMax-M2.5",
		"xiaomi/mimo-v2.6-pro",
		"xiaomi/mimo-v2.6-pro-ultraspeed",
		"xiaomi/mimo-v2.6-flash",
		"xiaomi/mimo-v2.5-pro",
		"xiaomi/mimo-v2.5",
		"Qwen/Qwen3.8-Omni-Flash",
		"Qwen/Qwen3.8-Max-0902",
		"Qwen/Qwen3.8-Max",
		"Qwen/Qwen3.8-27B",
		"Qwen/Qwen3.8-Flash",
		"Qwen/Qwen3.7-Max",
		"Qwen/Qwen3.7-Plus",
		"Qwen/Qwen3.7-Flash",
		"Qwen/Qwen3.6-Max-Preview",
		"Qwen/Qwen3.6-Plus",
		"meituan/LongCat-2.0",
		"stepfun/Step-5-Preview",
		"stepfun/Step-3.7-Flash",
		"stepfun/Step-3.5-Flash",
		"tencent/hy3-paid",
		"tencent/hy4-preview",
		"google/gemini-3.8-flash",
		"google/gemini-3.7-flash",
		"google/gemini-3.6-flash",
		"google/gemini-3.5-flash",
		"google/gemini-3.5-flash-lite",
		"google/gemini-3.1-flash-lite",
		"sakana/fugu-ultra",
		"nvidia/nemotron-3-ultra-550b-a55b",
		"thinkingmachines/inkling",
		"thinkingmachines/inkling-small",
		"stealth/glyph-cluster:free",
		"poolside/laguna-s-2.1-free",
		"inclusionai/ling-3.0-flash-sante:free",
		"inclusionai/ling-3.1-flash:free",
		"meta/muse-spark-1.1",
		"meta/muse-spark-1.2",
		"meta/muse-spark-1.2-contributor",
		"meta/muse-spark-1.3",
		"meta/muse-spark-1.3-contributor",
		"xai/grok-4.5",
		"xai/grok-4.6",
		"xai/grok-4.7",
		"mistral/mistral-large-4",
	},
	"individual-ultra": {
		"claude-sonnet-5-5",
		"claude-sonnet-5",
		"claude-sonnet-4-6",
		"claude-fable-5-1",
		"claude-fable-5",
		"claude-opus-5-5",
		"claude-opus-5",
		"claude-opus-4-8",
		"claude-opus-4-7",
		"claude-haiku-5-5",
		"claude-haiku-4-5-20251001",
		"gpt-6-astra",
		"gpt-6.1-sol",
		"gpt-6-sol",
		"gpt-6-luna",
		"gpt-5.6-sol",
		"gpt-5.6-terra",
		"gpt-5.6-luna",
		"gpt-5.5",
		"gpt-5.4",
		"gpt-5.3-codex",
		"gpt-5.4-mini",
		"deepseek/deepseek-v4-pro",
		"deepseek/deepseek-v4-flash",
		"deepseek/deepseek-v4-flash-vision-exp",
		"deepseek/deepseek-v4-flash-fast",
		"deepseek/deepseek-v4.1-flash",
		"deepseek/deepseek-v4.1-flash-fast",
		"moonshotai/Kimi-K3",
		"moonshotai/Kimi-K2.7-Code",
		"moonshotai/Kimi-K2.7-Code-Highspeed",
		"moonshotai/Kimi-K2.6",
		"moonshotai/Kimi-K2.5",
		"z-ai/glm-5.3-flash",
		"z-ai/glm-5.3-flashx",
		"zai-org/GLM-5.3",
		"zai-org/GLM-5.2",
		"zai-org/GLM-5.2-Fast",
		"zai-org/GLM-5.1",
		"zai-org/GLM-5",
		"MiniMaxAI/MiniMax-M3",
		"MiniMaxAI/MiniMax-M2.7",
		"MiniMaxAI/MiniMax-M2.5",
		"xiaomi/mimo-v2.6-pro",
		"xiaomi/mimo-v2.6-pro-ultraspeed",
		"xiaomi/mimo-v2.6-flash",
		"xiaomi/mimo-v2.5-pro",
		"xiaomi/mimo-v2.5",
		"Qwen/Qwen3.8-Omni-Flash",
		"Qwen/Qwen3.8-Max-0902",
		"Qwen/Qwen3.8-Max",
		"Qwen/Qwen3.8-27B",
		"Qwen/Qwen3.8-Flash",
		"Qwen/Qwen3.7-Max",
		"Qwen/Qwen3.7-Plus",
		"Qwen/Qwen3.7-Flash",
		"Qwen/Qwen3.6-Max-Preview",
		"Qwen/Qwen3.6-Plus",
		"meituan/LongCat-2.0",
		"stepfun/Step-5-Preview",
		"stepfun/Step-3.7-Flash",
		"stepfun/Step-3.5-Flash",
		"tencent/hy3-paid",
		"tencent/hy4-preview",
		"google/gemini-3.8-flash",
		"google/gemini-3.7-flash",
		"google/gemini-3.6-flash",
		"google/gemini-3.5-flash",
		"google/gemini-3.5-flash-lite",
		"google/gemini-3.1-flash-lite",
		"sakana/fugu-ultra",
		"nvidia/nemotron-3-ultra-550b-a55b",
		"thinkingmachines/inkling",
		"thinkingmachines/inkling-small",
		"stealth/glyph-cluster:free",
		"poolside/laguna-s-2.1-free",
		"inclusionai/ling-3.0-flash-sante:free",
		"inclusionai/ling-3.1-flash:free",
		"meta/muse-spark-1.1",
		"meta/muse-spark-1.2",
		"meta/muse-spark-1.2-contributor",
		"meta/muse-spark-1.3",
		"meta/muse-spark-1.3-contributor",
		"xai/grok-4.5",
		"xai/grok-4.6",
		"xai/grok-4.7",
		"mistral/mistral-large-4",
	},
	"teams-pro": {
		"claude-sonnet-5-5",
		"claude-sonnet-5",
		"claude-sonnet-4-6",
		"claude-haiku-5-5",
		"claude-haiku-4-5-20251001",
		"gpt-6-sol",
		"gpt-6-luna",
		"gpt-5.6-sol",
		"gpt-5.6-terra",
		"gpt-5.6-luna",
		"gpt-5.5",
		"gpt-5.4",
		"gpt-5.3-codex",
		"gpt-5.4-mini",
		"deepseek/deepseek-v4-pro",
		"deepseek/deepseek-v4-flash",
		"deepseek/deepseek-v4-flash-vision-exp",
		"deepseek/deepseek-v4-flash-fast",
		"deepseek/deepseek-v4.1-flash",
		"deepseek/deepseek-v4.1-flash-fast",
		"moonshotai/Kimi-K3",
		"moonshotai/Kimi-K2.7-Code",
		"moonshotai/Kimi-K2.7-Code-Highspeed",
		"moonshotai/Kimi-K2.6",
		"moonshotai/Kimi-K2.5",
		"z-ai/glm-5.3-flash",
		"z-ai/glm-5.3-flashx",
		"zai-org/GLM-5.3",
		"zai-org/GLM-5.2",
		"zai-org/GLM-5.2-Fast",
		"zai-org/GLM-5.1",
		"zai-org/GLM-5",
		"MiniMaxAI/MiniMax-M3",
		"MiniMaxAI/MiniMax-M2.7",
		"MiniMaxAI/MiniMax-M2.5",
		"xiaomi/mimo-v2.6-pro",
		"xiaomi/mimo-v2.6-pro-ultraspeed",
		"xiaomi/mimo-v2.6-flash",
		"xiaomi/mimo-v2.5-pro",
		"xiaomi/mimo-v2.5",
		"Qwen/Qwen3.8-Omni-Flash",
		"Qwen/Qwen3.8-Max-0902",
		"Qwen/Qwen3.8-Max",
		"Qwen/Qwen3.8-27B",
		"Qwen/Qwen3.8-Flash",
		"Qwen/Qwen3.7-Max",
		"Qwen/Qwen3.7-Plus",
		"Qwen/Qwen3.7-Flash",
		"Qwen/Qwen3.6-Max-Preview",
		"Qwen/Qwen3.6-Plus",
		"meituan/LongCat-2.0",
		"stepfun/Step-5-Preview",
		"stepfun/Step-3.7-Flash",
		"stepfun/Step-3.5-Flash",
		"tencent/hy3-paid",
		"tencent/hy4-preview",
		"google/gemini-3.8-flash",
		"google/gemini-3.7-flash",
		"google/gemini-3.6-flash",
		"google/gemini-3.5-flash",
		"google/gemini-3.5-flash-lite",
		"google/gemini-3.1-flash-lite",
		"nvidia/nemotron-3-ultra-550b-a55b",
		"thinkingmachines/inkling",
		"thinkingmachines/inkling-small",
		"stealth/glyph-cluster:free",
		"poolside/laguna-s-2.1-free",
		"inclusionai/ling-3.0-flash-sante:free",
		"inclusionai/ling-3.1-flash:free",
		"meta/muse-spark-1.1",
		"meta/muse-spark-1.2",
		"meta/muse-spark-1.2-contributor",
		"meta/muse-spark-1.3",
		"meta/muse-spark-1.3-contributor",
		"xai/grok-4.5",
		"xai/grok-4.6",
		"xai/grok-4.7",
		"mistral/mistral-large-4",
	},
	"unknown-plan-x": {
		"claude-sonnet-5-5",
		"claude-sonnet-5",
		"claude-sonnet-4-6",
		"claude-fable-5-1",
		"claude-fable-5",
		"claude-opus-5-5",
		"claude-opus-5",
		"claude-opus-4-8",
		"claude-opus-4-7",
		"claude-haiku-5-5",
		"claude-haiku-4-5-20251001",
		"gpt-6-astra",
		"gpt-6.1-sol",
		"gpt-6-sol",
		"gpt-6-luna",
		"gpt-5.6-sol",
		"gpt-5.6-terra",
		"gpt-5.6-luna",
		"gpt-5.5",
		"gpt-5.4",
		"gpt-5.3-codex",
		"gpt-5.4-mini",
		"deepseek/deepseek-v4-pro",
		"deepseek/deepseek-v4-flash",
		"deepseek/deepseek-v4-flash-vision-exp",
		"deepseek/deepseek-v4-flash-fast",
		"deepseek/deepseek-v4.1-flash",
		"deepseek/deepseek-v4.1-flash-fast",
		"moonshotai/Kimi-K3",
		"moonshotai/Kimi-K2.7-Code",
		"moonshotai/Kimi-K2.7-Code-Highspeed",
		"moonshotai/Kimi-K2.6",
		"moonshotai/Kimi-K2.5",
		"z-ai/glm-5.3-flash",
		"z-ai/glm-5.3-flashx",
		"zai-org/GLM-5.3",
		"zai-org/GLM-5.2",
		"zai-org/GLM-5.2-Fast",
		"zai-org/GLM-5.1",
		"zai-org/GLM-5",
		"MiniMaxAI/MiniMax-M3",
		"MiniMaxAI/MiniMax-M2.7",
		"MiniMaxAI/MiniMax-M2.5",
		"xiaomi/mimo-v2.6-pro",
		"xiaomi/mimo-v2.6-pro-ultraspeed",
		"xiaomi/mimo-v2.6-flash",
		"xiaomi/mimo-v2.5-pro",
		"xiaomi/mimo-v2.5",
		"Qwen/Qwen3.8-Omni-Flash",
		"Qwen/Qwen3.8-Max-0902",
		"Qwen/Qwen3.8-Max",
		"Qwen/Qwen3.8-27B",
		"Qwen/Qwen3.8-Flash",
		"Qwen/Qwen3.7-Max",
		"Qwen/Qwen3.7-Plus",
		"Qwen/Qwen3.7-Flash",
		"Qwen/Qwen3.6-Max-Preview",
		"Qwen/Qwen3.6-Plus",
		"meituan/LongCat-2.0",
		"stepfun/Step-5-Preview",
		"stepfun/Step-3.7-Flash",
		"stepfun/Step-3.5-Flash",
		"tencent/hy3-paid",
		"tencent/hy4-preview",
		"google/gemini-3.8-flash",
		"google/gemini-3.7-flash",
		"google/gemini-3.6-flash",
		"google/gemini-3.5-flash",
		"google/gemini-3.5-flash-lite",
		"google/gemini-3.1-flash-lite",
		"sakana/fugu-ultra",
		"nvidia/nemotron-3-ultra-550b-a55b",
		"thinkingmachines/inkling",
		"thinkingmachines/inkling-small",
		"stealth/glyph-cluster:free",
		"poolside/laguna-s-2.1-free",
		"inclusionai/ling-3.0-flash-sante:free",
		"inclusionai/ling-3.1-flash:free",
		"meta/muse-spark-1.1",
		"meta/muse-spark-1.2",
		"meta/muse-spark-1.2-contributor",
		"meta/muse-spark-1.3",
		"meta/muse-spark-1.3-contributor",
		"xai/grok-4.5",
		"xai/grok-4.6",
		"xai/grok-4.7",
		"mistral/mistral-large-4",
	},
}

// planTierByName mirrors the reference's subscription fixture.
var planTierByName = map[string]*int{
	"individual-go":       intp(0),
	"individual-go-v1":    intp(0),
	"individual-goat":     intp(1),
	"individual-pro":      intp(2),
	"individual-pro-v1":   intp(2),
	"individual-provider": intp(3),
	"individual-max":      intp(4),
	"individual-ultra":    intp(4),
	"teams-pro":           intp(2),
}

func intp(v int) *int { return &v }

func setOf(items []string) map[string]struct{} {
	out := make(map[string]struct{}, len(items))
	for _, i := range items {
		out[i] = struct{}{}
	}
	return out
}

// TestFilterMatchesReferenceForEveryPlan asserts, for each plan, that our
// filter keeps exactly the models the reference keeps - no more, no less.
func TestFilterMatchesReferenceForEveryPlan(t *testing.T) {
	for planID, tier := range planTierByName {
		want, ok := wantVisibleByPlan[planID]
		if !ok {
			t.Fatalf("no reference expectation for %s", planID)
		}
		got := FilterModels(liveCatalog87, []*BillingAccess{{TierWeight: tier}})
		gotSet, wantSet := setOf(got), setOf(want)

		for _, id := range got {
			if _, ok := wantSet[id]; !ok {
				t.Errorf("%s: kept a model the reference hides: %s", planID, id)
			}
		}
		for _, id := range want {
			if _, ok := gotSet[id]; !ok {
				t.Errorf("%s: hid a model the reference keeps: %s", planID, id)
			}
		}
		if len(got) != len(want) {
			t.Errorf("%s: count %d, reference %d", planID, len(got), len(want))
		}
	}
}

// TestGoPlanSeesExactlyTheReferenceGoSet pins the operator-facing case: a Go
// account must see exactly 55 of the 87, not 26 (a stale third-party table) and
// not all 87.
func TestGoPlanSeesExactlyTheReferenceGoSet(t *testing.T) {
	tier := intp(0)
	got := FilterModels(liveCatalog87, []*BillingAccess{{TierWeight: tier}})
	const want = 55
	if len(got) != want {
		t.Fatalf("Go plan sees %d models, want %d", len(got), want)
	}
}

// TestFilterFailsOpen covers every "uncertainty keeps the model" rule. Each of
// these hiding a model would be a silent, hard-to-notice loss.
func TestFilterFailsOpen(t *testing.T) {
	all := len(liveCatalog87)

	if n := len(FilterModels(liveCatalog87, nil)); n != all {
		t.Errorf("no accounts: kept %d, want all %d (empty pool shows everything)", n, all)
	}
	if n := len(FilterModels(liveCatalog87, []*BillingAccess{})); n != all {
		t.Errorf("empty pool: kept %d, want all %d", n, all)
	}
	if n := len(FilterModels(liveCatalog87, []*BillingAccess{{}})); n != all {
		t.Errorf("unknown tier: kept %d, want all %d", n, all)
	}
	if n := len(FilterModels(liveCatalog87, []*BillingAccess{{TierWeight: intp(0), OnDemandCredits: 5}})); n != all {
		t.Errorf("on-demand credits: kept %d, want all %d", n, all)
	}
	// A model absent from the table must stay visible: the table can lag
	// upstream, and hiding a brand-new model would be the worst case.
	if !ModelVisibleInPlan("brand-new-model-not-in-table", &BillingAccess{TierWeight: intp(0)}) {
		t.Error("a model missing from the table was hidden; unknown models must fail open")
	}
	// An unrecognised planId must not be treated as the lowest tier.
	if !ModelVisibleInPlan("claude-opus-5-5", AccessFor(SubscriptionPlanFor("some-future-plan"), 0)) {
		t.Error("unknown planId hid a model; unknown plans must fail open")
	}
}

// TestFilterUsesUnionAcrossAccounts pins the pool rule the operator asked for:
// with several plans, a model shows if ANY of them includes it.
func TestFilterUsesUnionAcrossAccounts(t *testing.T) {
	pool := []*BillingAccess{{TierWeight: intp(0)}, {TierWeight: intp(2)}} // Go + Pro
	got := FilterModels(liveCatalog87, pool)
	proOnly := FilterModels(liveCatalog87, []*BillingAccess{{TierWeight: intp(2)}})
	if len(got) != len(proOnly) {
		t.Fatalf("Go+Pro union kept %d, Pro alone %d (Pro superset of Go, so they must match)", len(got), len(proOnly))
	}
	// The union must be strictly larger than Go alone, or the rule is not
	// actually unioning.
	goOnly := FilterModels(liveCatalog87, []*BillingAccess{{TierWeight: intp(0)}})
	if len(got) <= len(goOnly) {
		t.Errorf("union (%d) is not larger than Go alone (%d)", len(got), len(goOnly))
	}
}

// TestSubscriptionPlanResolution pins longest-prefix matching: "individual-goat"
// must not resolve as "individual-go".
func TestSubscriptionPlanResolution(t *testing.T) {
	cases := map[string]struct {
		name string
		tier int
	}{
		"individual-go":       {"Go", 0},
		"individual-go-v1":    {"Go", 0},
		"individual-goat":     {"GOAT", 1},
		"individual-pro":      {"Pro", 2},
		"individual-pro-v1":   {"Pro", 2},
		"individual-provider": {"Provider", 3},
		"individual-max":      {"Max", 4},
		"individual-ultra":    {"Ultra", 4},
		"teams-pro":           {"Teams Pro", 2},
		"individual_goat":     {"GOAT", 1}, // underscore normalisation
	}
	for id, want := range cases {
		p := SubscriptionPlanFor(id)
		if p == nil {
			t.Errorf("%s: no plan resolved", id)
			continue
		}
		if p.Name != want.name || p.TierWeight != want.tier {
			t.Errorf("%s: got %s/%d, want %s/%d", id, p.Name, p.TierWeight, want.name, want.tier)
		}
	}
	if SubscriptionPlanFor("nonsense") != nil {
		t.Error("an unrecognised planId resolved to a plan; it must return nil so callers fail open")
	}
}

// TestTableSnapshotIntegrity guards the ported table's shape. It cannot tell
// whether an entry is correct (only the reference can), but it catches the
// mechanical failure modes: a truncated table, or a tier name that is not on
// the scale.
func TestTableSnapshotIntegrity(t *testing.T) {
	const wantEntries = 85
	if len(knownPlans) != wantEntries {
		t.Fatalf("knownPlans has %d entries, want %d (table truncated during a port?)", len(knownPlans), wantEntries)
	}
	for id, tier := range knownPlans {
		if _, ok := planOrder[tier]; !ok {
			t.Errorf("model %q has tier %q which is not on the plan scale", id, tier)
		}
	}
	for _, tier := range planTierOrder {
		if _, ok := planOrder[tier]; !ok {
			t.Errorf("plan scale lists %q but planOrder has no rank for it", tier)
		}
	}
	if len(planOrder) != len(planTierOrder) {
		t.Errorf("planOrder has %d ranks for %d tiers", len(planOrder), len(planTierOrder))
	}
}
